### ISSUE TITLE
升级到最新版本无法发布

### ISSUE THREAD

**Issue by easyboot** [dotnet-campus/dotnetcampus.DotNETBuildSDK#102]
![image](https://github.com/dotnet-campus/dotnetcampus.DotNETBuildSDK/assets/26960023/2ee5ab21-cf98-4278-a443-d0b6f8ebec2e)
我升级到最新版本，总是提示命令未发现。重新安装也不行

**Comment by easyboot** [comment]
![image](https://github.com/dotnet-campus/dotnetcampus.DotNETBuildSDK/assets/26960023/034e71c4-298e-4528-a09a-f3b00d1eb68b)
找到问题所在了，需要把这个文件中.net5改为.net6,就正常了

**Comment by lindexi** [comment]
@easyboot 感谢，我立刻修复此问题

**Comment by lindexi** [comment]
@easyboot 请试试 3.10.1 版本，预计我修复了此问题
